# Generated by Django 4.1 on 2022-09-04 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoderApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='cumpleanios',
            field=models.DateField(default=datetime.date(2022, 9, 4)),
        ),
    ]
