# Generated by Django 4.1 on 2022-09-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoderApp', '0002_alter_mascotas_cumpleanios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='cumpleanios',
            field=models.DateField(blank=True, null=True),
        ),
    ]
